version: "3"

services:
    url-shortener:
        build: ./url-shortener-backend
        ports:
            - 8080:8080
        container_name: url-shortener-java
        depends_on:
            - mongo
        networks:
            - shared-net
    mongo:
        image: "mongo"
        ports:
            - 27017:27017
        volumes:
            - ./url-shortener-db:/data/db/
        hostname: mongo
        container_name: url-shortener-mongo
        networks:
            - shared-net
networks:
    shared-net:
        driver: bridge
