# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: URL Shortener Docker CD

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: mvn install and package
        run: |
          mvn clean install
          mvn package
      - uses: actions/upload-artifact@master
        with:
          name: mvn artifacts
          path: target/
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-lastest, macos-latest]
        java-version: [11]

    steps:
      - uses: actions/checkout@v2
      - name: Use Java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - uses: actions/download-artifact@master
        with:
          name: mvn artifacts
          path: target
      - name: mvn install, and test
        run: |
          mvn install
          mvn test
        env:
          CI: true
          
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download built artifact
      uses: actions/download-artifact@main
      with:
        name: mvn artifacts
        path: target
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{github.actor}}
        password: ${{secrets.DOCKER_PASSWORD}}
        registry: docker.pkg.github.com
        repository: urls/url-shortener/url-shortener
        tag_with_sha: true
