name: URL Shortener Docker CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: mvn install and package
        run: |
          mvn clean install
          mvn package
      - uses: actions/upload-artifact@master
        with:
          name: mvn artifacts
          path: target/
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-lastest, macos-latest ]
        java-version: [ 11 ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - uses: actions/download-artifact@master
        with:
          name: mvn artifacts
          path: target
      - name: mvn install, and test
        run: |
          mvn install
          mvn test
        env:
          CI: true
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download built artifact
        uses: actions/download-artifact@main
        with:
          name: mvn artifacts
          path: target
      - name: Docker Images Present
        run: docker images
      - name: Build Docker image
        run: docker build -t url-shortener:latest .
      - name: Docker Images Present After Building
        run: docker images
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: urls
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Docker Tag and Push
        run: |
          docker tag url-shortener:latest ghcr.io/urls/url-shortner/url-shortner:latest
          docker push ghcr.io/urls/url-shortner/url-shortner:latest