name: URL Shortener Docker CD

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2
            - name: gradle install and package
              run: |
                  cd url-shortener-backend
                  ./gradlew clean build --info
    test:
        runs-on: ubuntu-latest
        needs: build
        strategy:
            matrix:
                os: [ubuntu-lastest, macos-latest]
                java-version: [11]
        steps:
            - uses: actions/checkout@v2
            - name: Use Java ${{ matrix.java-version }}
              uses: actions/setup-java@v2
              with:
                  java-version: ${{ matrix.java-version }}
                  distribution: "adopt"
            - name: mvn install, and test
              run: |
                  cd url-shortener-backend
                  ./gradlew clean
                  ./gradlew build
              env:
                  CI: true
    Build-and-Push-Docker-Image:
        runs-on: ubuntu-latest
        needs: test
        name: Docker Build, Tag, Push
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Generate WAR for URL-Shortener
              run: |
                  cd url-shortener-backend
                  ./gradlew build
            - name: Build Docker image
              run: |
                  cd url-shortener-backend
                  docker build -t url-shortener:latest .
            - name: Login to GitHub Packages Docker Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.DOCKER_SECRET }}
            - name: Docker Tag and Push
              run: |
                  docker tag url-shortener:latest ghcr.io/urls/url-shortener:latest
                  docker push ghcr.io/urls/url-shortener:latest
